<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cisharpai\Cisharpai.csproj" />
    <ProjectReference Include="..\Cisharpai.OpenAi\Cisharpai.OpenAi.csproj" />
    <ProjectReference Include="..\Cisharpai.Anthropic\Cisharpai.Anthropic.csproj" />
    <ProjectReference Include="..\Cisharpai.AzureOpenAi\Cisharpai.AzureOpenAi.csproj" />
    <ProjectReference Include="..\Cisharpai.Cohere\Cisharpai.Cohere.csproj" />
  </ItemGroup>

</Project>
